### ISSUE TITLE
crash tolerance and max temp changes

### ISSUE THREAD

**Issue by shdwlrd** [zer0Kerbal/DaMichel#2]
looking through the configs for the fuselage parts, I noticed that the crash tolerance is 10m/s. That's awfully low considering most of the Mk2, Mk3, and aero parts have a crash tolerance of 50m/s. (I have looked at the crash tolerances for the stock Mk1 space plane parts, that explains a lot. IRL planes are nowhere near that fragile. You may tear off a wing, but the plane shouldn't explode with a 22mph/35kph impact.)

Also the max temps are too high. The stock Mk1 parts are at 1800-2000 and the Mk2 & Mk3 parts are at 2500 & 2700. The parts are set at 2800, much higher than the Mk1 parts that these are geared for.

**Comment by zer0Kerbal** [comment]
excellent observation, very logical rational thought, well presented, and great suggestions.
I will be posting here and on the forums what I have come up with - still malleable

**Comment by zer0Kerbal** [comment]
## DMfuselage-intake - has the same specs as the Ram Air Intake.
	TechRequired = highAltitudeFlight
	entryCost = 14000 // was 1600
	cost = 2680 // was 2000

	mass = 0.125 // stock part 0.06
	dragModelType = default
	maximum_drag = 0.3
	minimum_drag = 0.3
	angularDrag = 1
	crashTolerance = 7
	breakingForce = 200 // was 50
	breakingTorque = 200 // was 50
	maxTemp = 2000 // was 2900
	thermalMassModifier = 12.0 // added
	// heatConductivity = 0.06  // added // half default
	buoyancy = 0.1  // added

	explosionPotential = 0.5  // added
	
		MODULE
	{
		name = ModuleResourceIntake
		resourceName = IntakeAir
		checkForOxygen = true
		area = 0.01
		intakeSpeed = 10
		intakeTransformName = intakeTransform
 // added
		machCurve
		{
			key = 0 0.85 0 0
			key = 1 1 0 0
			key = 2 0.95 -0.08751557 -0.08751557
			key = 4 0.5 -0.4034287 -0.4034287
			key = 8 0.01 0 0
		 }
	}

	RESOURCE
	{
		name = IntakeAir
		amount = 2.0 // was 0.2
		maxAmount = 2.0 // was 0.2
	}

**Comment by zer0Kerbal** [comment]
@shdwlrd everything should now be updated for this - at least for fuselage. kindly tell me what you think.
👍 
[changelog](https://github.com/zer0Kerbal/DaMichel/blob/master/GameData/DaMichel/Fuselage/Changelog.cfg)

**Comment by zer0Kerbal** [comment]
[#2](https://github.com/zer0Kerbal/DaMichel/releases/tag/DFF-1.1.0.1)
