### ISSUE TITLE
MM Error

### ISSUE THREAD

**Issue by TexasKimchi** [zer0Kerbal/DaMichel#4]
[ERR 07:53:14.379] Error - Skipping a patch subnode with unbalanced square brackets or a space (replace them with a '?') in @PART[DM-SphericalTank-125-70,DM-SphericalTank-125-140,DM-SphericalTank-125-111,DM-SphericalTank-125-88,DM-SphericalTank-125-55]:NEEDS[B9PartSwitch,Karbonite,DaMichel/SphericalTanks]:AFTER[SphericalTanks] : 
@MODULE[ModuleB9PartSwitch]:HAS[#moduleID[SphericalTankFuelSwitch]

**Comment by ebmocces** [comment]
I've fixed this in https://github.com/zer0Kerbal/DaMichel/pull/6

**Comment by ebmocces** [comment]
I guess @zer0Kerbal doesn't want to keep this mod updated?

**Comment by 7ranceaddic7** [comment]
I guess you should realize that this is his mod that he does on his time. You're cattiness be damn.

**Comment by zer0Kerbal** [comment]
- [x] #6
