### ISSUE TITLE
DragCube Config Errors

### ISSUE THREAD

**Issue by 7ranceaddic7** [zer0Kerbal/DaMichel#7]
Logging this for reference.

DragCube: Config string does not have correct number of values

https://forum.kerbalspaceprogram.com/index.php?/topic/191719-181-damichels-parts-11002020-02-17/&do=findComment&comment=3789424

[LOG 21:07:31.497] PartLoader: Compiling Part 'DaMichel/CargoBays/Parts/250/dm-round-cargobay250-1/dm-round-cargobay250-1'
[ERR 21:07:31.519] DragCube: Config string does not have correct number of values

[LOG 21:07:31.608] PartLoader: Compiling Part 'DaMichel/CargoBays/Parts/250/dm-round-cargobay250-1/dm-round-cargobay-1'
[ERR 21:07:31.626] DragCube: Config string does not have correct number of values

[LOG 21:07:31.907] PartLoader: Compiling Part 'DaMichel/CargoBays/Parts/375/dm-round-cargobay375-1/dm-round-cargobay375-1'
[ERR 21:07:31.921] DragCube: Config string does not have correct number of values

**Comment by zer0Kerbal** [comment]
thank you! 
@7ranceaddic7 splitting this mod up - moved issue to SphericalTanks.
